version: '3'

services:
  app_proposta:
    image: 'proposta:latest'
    build:
      context: .
    container_name: app 
    ports:
      - "8080:8080"
    networks:
      - production-network
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/projeto_proposta
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postzup
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.PostgreSQLDialect
  db:
    image: 'postgres:13'
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postzup
      - POSTGRES_DB=projeto_proposta
    networks:
      - production-network  
networks:
  production-network:
    driver: bridge   